### ISSUE TITLE
Make dropper download big executables

### ISSUE THREAD

**Issue by tugdualnicolas** [D4Vinci/Dr0p1t-Framework#17]
I have tried to generate on Kali and Win 10 same result. The dropper connect to the download server but download only 32ko and the trojan is 32mo.

**Comment by D4Vinci** [comment]
What kind of trojan is 32 mega!!

**Comment by tugdualnicolas** [comment]
Oops fail 3.2mo

**Comment by D4Vinci** [comment]
This is from the library not me but..
I will make an update to fix all the error in the dropper at the end of this week

**Comment by tugdualnicolas** [comment]
Ok thx :)

**Comment by hostbob** [comment]
@tugdualnicolas how were you able to compile this without pyinstaller error?

**Comment by tugdualnicolas** [comment]
Try to reinstall wine or manually install python 2.7 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tugdualnicolas** [comment]
Info here : https://appdb.winehq.org/objectManager.php?sClass=version&iId=21957 @hostbob

**Comment by D4Vinci** [comment]
Fixed in 1.3.1 update check it out!

**Comment by tugdualnicolas** [comment]
Still getting the Error... :/ sry

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by D4Vinci** [comment]
I tested it with 10 mega file,the error from you
